### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by hgeldenhuys** [wbkd/react-flow#1953]
### Describe the Bug

I'm using React Flow with Remix, and getting the following error when running example code:

`Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/user/Emerge/flow/node_modules/.pnpm/react-flow-renderer@10.0.0-next.51_react-dom@17.0.2+react@17.0.2/node_modules/react-flow-renderer/dist/esm/index.js from /Users/user/Emerge/flow/build/index.js not supported.
Instead change the require of /Users/user/Emerge/flow/node_modules/.pnpm/react-flow-renderer@10.0.0-next.51_react-dom@17.0.2+react@17.0.2/node_modules/react-flow-renderer/dist/esm/index.js in /Users/user/Emerge/flow/build/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/user/Emerge/flow/build/index.js:395:43)
    at /Users/user/Emerge/flow/node_modules/.pnpm/@remix-run+serve@1.2.3_react-dom@17.0.2+react@17.0.2/node_modules/@remix-run/serve/index.js:40:17
    at Layer.handle [as handle_request] (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/layer.js:95:5)
    at /Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/index.js:281:22
    at param (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/index.js:360:14)
    at param (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/index.js:416:3)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/index.js:275:10)
    at logger (/Users/user/Emerge/flow/node_modules/.pnpm/morgan@1.10.0/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/index.js:323:13)
    at /Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/index.js:341:12)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/user/Emerge/flow/node_modules/.pnpm/serve-static@1.14.2/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:390:28)
    at SendStream.error (/Users/user/Emerge/flow/node_modules/.pnpm/send@0.17.2/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/user/Emerge/flow/node_modules/.pnpm/send@0.17.2/node_modules/send/index.js:421:12)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/send@0.17.2/node_modules/send/index.js:763:28)
    at /Users/user/Emerge/flow/node_modules/.pnpm/send@0.17.2/node_modules/send/index.js:771:23
    at FSReqCallback.oncomplete (node:fs:198:21)`

### Your Example Website or App

https://stackblitz.com/edit/node-xkwl6v?file=app%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

See stackblitz. Just install v10 branch and get any example loading

### Expected behavior

As a developer I except the compiler to be happy so that there is peace in the world

### Platform

- OS: MacOS latest
- Browser: Chrome latest
- Version: v10

**Comment by moklick** [comment]
Hey @hgeldenhuys thanks for the hint! We will check how to fix this.

**Comment by BenEinwechter** [comment]
It looks like this commit https://github.com/wbkd/react-flow/commit/9156a22a2841be0ff82a3d479cf98c9854a9a6b5 removed support for CJS, but I imagine a large number of projects are still on CJS. On my Next.js we haven't been able to switch to using only ESM due to other libraries we're using. Is is possible to release react-flow-renderer with both ESM and CJS build targets like you had before? Then we could import from whichever version we need.

Thanks for all your work on this amazing library!

**Comment by moklick** [comment]
Hey @BenEinwechter 

we wanted to do some cleanup. A lot of libraries are ESM only. With older nextjs versions you can use https://github.com/martpie/next-transpile-modules .

@hgeldenhuys I haven't tried it, but does this help you https://remix.run/docs/en/v1/api/conventions#serverdependenciestobundle ?

**Comment by hgeldenhuys** [comment]
Thanks @moklick for the info. I might be a bit out of my depth to be able to make this work, but when making the recommended changes:
```javascript
/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: [".*"],
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    "react-flow-renderer",
    "d3-zoom",
    "d3-dispatch",
    "d3-drag",
    "d3-selection",
    "d3-interpolate",
    "d3-transition",
    "d3-color",
    "d3-timer",
    "d3-ease",
  ],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  // devServerPort: 8002
};
```

I now get the following:
```
TypeError: (0 , import_context.default) is not a function
    at Object.<anonymous> (/Users/user/Emerge/flow/build/index.js:4172:49)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/user/Emerge/flow/node_modules/.pnpm/@remix-run+serve@1.2.3_react-dom@17.0.2+react@17.0.2/node_modules/@remix-run/serve/index.js:40:17
    at Layer.handle [as handle_request] (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/user/Emerge/flow/node_modules/.pnpm/express@4.17.3/node_modules/express/lib/router/route.js:137:13)```

not sure if that now is part of the same issue, or if this is a remix issue now?

**Comment by moklick** [comment]
I added an UMD build in v10.1.0. React Flow works with Stackblitz and Remix now.
